# Generated by Django 4.1.7 on 2023-04-09 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_alter_historicalproduct_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalindicator", name="category_product",
        ),
        migrations.RemoveField(model_name="historicalindicator", name="history_user",),
        migrations.RemoveField(
            model_name="historicalmeasureunit", name="history_user",
        ),
        migrations.RemoveField(
            model_name="historicalproduct", name="category_product",
        ),
        migrations.RemoveField(model_name="historicalproduct", name="history_user",),
        migrations.RemoveField(model_name="historicalproduct", name="measure_unit",),
        migrations.DeleteModel(name="HistoricalCategoryProduct",),
        migrations.DeleteModel(name="HistoricalIndicator",),
        migrations.DeleteModel(name="HistoricalMeasureUnit",),
        migrations.DeleteModel(name="HistoricalProduct",),
    ]
